import { Toaster } from "@/components/ui/sonner"
import { TooltipProvider } from "@/components/ui/tooltip"
import { NuqsProvider } from "@/context/NuqsProvider"
import SuspenseProvider from "@/context/SuspenseProvider"
import { QueryProvider } from "@/context/TanstackProvider"
import ConfirmDialogProvider from "@/context/confirm-dialog-provider"
import { cn } from "@/lib/utils"
import type { Metadata } from "next"
import { ThemeProvider } from "next-themes"
import { Inter, JetBrains_Mono } from "next/font/google"
import "./globals.css"

const inter = Inter({ subsets: ["latin"], variable: "--font-sans" })

const geistMono = JetBrains_Mono({
  subsets: ["latin"],
  variable: "--font-geist-mono",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" className={cn(inter.variable, geistMono.variable)}>
      <body className={`${inter.variable} ${geistMono.variable} antialiased`}>
      <ThemeProvider enableSystem attribute="class" defaultTheme="light" disableTransitionOnChange>
        <ConfirmDialogProvider>
          <QueryProvider>
            <NuqsProvider>
              <TooltipProvider>
                <SuspenseProvider>
                  {children}
                  <Toaster richColors />
                </SuspenseProvider>
              </TooltipProvider>
            </NuqsProvider>
          </QueryProvider>
        </ConfirmDialogProvider>
        </ThemeProvider>
      </body>
    </html>
  )
}
